"""Volume preparation before registration."""

from regix.preprocess.geometry import (
    body_mask,
    center_of_mass_physical,
    crop_to_mask,
    dilate_mask_mm,
    erode_mask_mm,
    image_center_physical,
    keep_largest_component,
    mask_bounding_box_mm,
    pad_to_multiple,
    principal_axes,
    reorient,
    resample_like,
    resample_to_spacing,
    unpad,
)
from regix.preprocess.intensity import (
    DEFAULT_PREP_BY_MODALITY,
    HU_WINDOWS,
    apply_intensity_prep,
    default_prep_for,
    n4_bias_correction,
    normalize_for_features,
    resolve_clip_bounds,
)

__all__ = [
    "DEFAULT_PREP_BY_MODALITY",
    "HU_WINDOWS",
    "apply_intensity_prep",
    "default_prep_for",
    "n4_bias_correction",
    "normalize_for_features",
    "resolve_clip_bounds",
    "body_mask",
    "center_of_mass_physical",
    "crop_to_mask",
    "dilate_mask_mm",
    "erode_mask_mm",
    "image_center_physical",
    "keep_largest_component",
    "mask_bounding_box_mm",
    "pad_to_multiple",
    "principal_axes",
    "reorient",
    "resample_like",
    "resample_to_spacing",
    "unpad",
]
