"""Registration engine: elastix parameters, initialization, execution, application."""

from regix.registration.convexadam import (
    DeformableResult,
    adam_instance_optimization,
    displacement_field_from_transform,
)
from regix.registration.engine import (
    ElastixEngine,
    RegistrationFailure,
    RegistrationOutcome,
    StageResult,
    apply_transform,
    set_output_grid,
)
from regix.registration.initialize import (
    InitCandidate,
    build_candidates,
    choose_initialization,
    geometry_init,
    moments_init,
    organ_centroid_init,
    organ_moments_init,
)
from regix.registration.itk_bridge import (
    engine_available,
    itk_to_sitk,
    itk_transform_to_sitk,
    sitk_to_itk,
)
from regix.registration.params import (
    ParamContext,
    build_parameter_map,
    describe_stage,
    read_parameter_file,
    required_image_count,
    resolve_metric,
    same_modality,
    to_itk_parameter_object,
    write_parameter_file,
)
from regix.registration.transforms import (
    compose,
    decompose_affine,
    flatten_linear,
    linear_matrix_from_transform,
    load_transform,
    matrix_moving_to_fixed,
    parameter_map_to_transform,
    save_transform,
    to_matrix_4x4,
    transform_to_elastix_initial,
    write_initial_transform_file,
)
from regix.registration.warp import (
    AppliedTransform,
    ElastixAppliedTransform,
    SitkAppliedTransform,
    transform_points_via_field,
    warp_landmarks_moving_to_fixed,
)

__all__ = [
    "ParamContext",
    "build_parameter_map",
    "describe_stage",
    "read_parameter_file",
    "required_image_count",
    "resolve_metric",
    "same_modality",
    "to_itk_parameter_object",
    "write_parameter_file",
    "engine_available",
    "itk_to_sitk",
    "itk_transform_to_sitk",
    "sitk_to_itk",
    "ElastixEngine",
    "RegistrationFailure",
    "RegistrationOutcome",
    "StageResult",
    "apply_transform",
    "set_output_grid",
    "InitCandidate",
    "build_candidates",
    "choose_initialization",
    "geometry_init",
    "moments_init",
    "organ_centroid_init",
    "organ_moments_init",
    "compose",
    "decompose_affine",
    "flatten_linear",
    "linear_matrix_from_transform",
    "load_transform",
    "matrix_moving_to_fixed",
    "parameter_map_to_transform",
    "save_transform",
    "to_matrix_4x4",
    "transform_to_elastix_initial",
    "write_initial_transform_file",
    "AppliedTransform",
    "ElastixAppliedTransform",
    "SitkAppliedTransform",
    "transform_points_via_field",
    "warp_landmarks_moving_to_fixed",
    "DeformableResult",
    "adam_instance_optimization",
    "displacement_field_from_transform",
]
